---
title: "Pre_Stream_Experimenting"
author: "Michael Mullarkey"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: no
      smooth_scroll: no
geometry: margin=0.50in
---

```{r setup, include=FALSE, cache = FALSE}
require("knitr")
## setting working directory
opts_knit$set(root.dir = "/Users/Carbonite/Documents/Github_R/palmer_penguins_example") ## Will need to change across computers
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE, warning = FALSE, message = FALSE, include = FALSE)

```

```{r}

if(!require(palmerpenguins)){install.packages('palmerpenguins')}
library(palmerpenguins)
if(!require(tidyverse)){install.packages('tidyverse')}
library(tidyverse)
if(!require(tidymodels)){install.packages('tidymodels')}
library(tidymodels)
if(!require(GGally)){install.packages('GGally')}
library(GGally)
if(!require(lubridate)){install.packages('lubridate')}
library(lubridate)

```

```{r reading in data}

## Let's load the Penguins data!

library(palmerpenguins)
data(package = 'palmerpenguins')

## Glimpse helps us get a sense of what kinds of dimensions, types of variables, and responses we have in our data frame

glimpse(penguins)

```

```{r using group by and tally}

## We can see how many species we have + how many of each species in our dataset

penguins %>% 
  group_by(species) %>% 
  tally()

## But how many are on each island? If we wanted to visit only one of the islands, what would be best for our penguin seeing buck?

penguins %>% 
  group_by(species, island) %>% 
  tally()

```

```{r visualizing distributions and relationships between species and island}

## Modified code from https://allisonhorst.github.io/palmerpenguins/articles/intro.html

## First doing this with species and island, not super intuitive, though bottom left column is basically what we get with our group_by above

penguins %>%
  dplyr::select(species, island) %>%
  GGally::ggpairs(aes(color = species)) +
  scale_colour_manual(values = c("darkorange","purple","cyan4")) +
  scale_fill_manual(values = c("darkorange","purple","cyan4"))

```


```{r expanding our plotting to other variables}
## Looking at Species and a numeric variable

penguins %>%
  dplyr::select(species, bill_length_mm) %>%
  GGally::ggpairs(aes(color = species)) +
  scale_colour_manual(values = c("darkorange","purple","cyan4")) +
  scale_fill_manual(values = c("darkorange","purple","cyan4"))

## Looking across all numberic variables other than year

penguins %>%
  dplyr::select(is.numeric, -year) %>%
  GGally::ggpairs(aes()) +
  scale_colour_manual(values = c("darkorange","purple","cyan4")) +
  scale_fill_manual(values = c("darkorange","purple","cyan4"))

## Adding in species for some more understanding and color. Also, makes more sense to have categorical variable first rather than last or in the middle for aesthetic purposes.

penguins %>%
  dplyr::select(species, is.numeric, -year) %>%
  GGally::ggpairs(aes(color = species)) +
  scale_colour_manual(values = c("darkorange","purple","cyan4")) +
  scale_fill_manual(values = c("darkorange","purple","cyan4"))

```
```{r calculating the mean across a bunch of variables at once}

## Taking the mean across a bunch of variables

penguins %>% 
  group_by(species) %>% 
  dplyr::summarise(across(
    is.numeric,
    mean
  ))

## What if we want to deal with NA values? We could ignore them first. We could also impute data, but probably makes more sense to talk about that in a later stream

penguins %>% 
  group_by(species) %>% 
  dplyr::summarise(across(
    is.numeric,
    ~mean(.x, na.rm = T)
  ))

## What if we don't want the year column?

## This version kind of works, but not really since we're missing body mass now

penguins %>% 
  group_by(species) %>% 
  dplyr::summarise(across(
    contains("mm"),
    ~mean(.x, na.rm = T)
  ))

## This version is probably easier in this case (Though demonstrates that there are a lot of ways to solve any problem in R)

penguins %>% 
  group_by(species) %>% 
  dplyr::summarise(across(
    is.numeric,
    ~mean(.x, na.rm = T)
  )) %>% 
  dplyr::select(-year)

```

```{r what if we want to get multiple summary statistics across variables at once}

penguins %>% 
  group_by(species) %>% 
  dplyr::summarise(across(
    .cols = is.numeric,
    .fns = list(mean = mean, sd = sd), na.rm = T,
    .names = "{col}_{fn}"
  )) %>% 
  dplyr::select(-contains("year"))

## We can select one variable at a time if we want to make this simpler/easier to read

penguins %>% 
  group_by(species) %>% 
  dplyr::summarise(across(
    .cols = is.numeric,
    .fns = list(mean = mean, sd = sd), na.rm = T,
    .names = "{col}_{fn}"
  )) %>% 
  dplyr::select(species, contains("bill_length")) 

```
```{r checking out the year variable}

## About an even number of penguins across 3 years

penguins %>% 
  group_by(year) %>% 
  tally()

```

